#file: noinspection ComposeUnknownValues
services:
  backend:
    image: ggorockee/backend:240912_2253
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1

  mysql:
    image: "mysql:oraclelinux9"
    ports:
      - "3306:3306"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - path: .mysql.env
        required: false
    volumes:
      - ./db-data/mysql:/var/lib/mysql

