#file: noinspection ComposeUnknownValues
services:
  backend:
    image: ggorockee/backend:240919_1658
    restart: always
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
    env_file: .mysql.env
        

  mysql:
    image: "mysql:oraclelinux9"
    ports:
      - "3306:3306"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file: .mysql.env
    volumes:
      - ./db-data/mysql:/var/lib/mysql

